- name: copy and deploy cluster
  hosts: web
  vars:
    asnible_python_interpreter: /usr/bin/python3
  become: true
  become_user: "{{ansible_user}}"
  
  tasks:
  - name: ensures minikube current conf dir exists
    file: 
      path: "/home/{{ansible_user}}/current_minikube_configs"
      state: directory
      
  - name: ensures minikube new conf dir exists
    file: 
      path: "/home/{{ansible_user}}/new_minikube_configs"
      state: directory

  - name: copy minikube deployment config to web
    ansible.builtin.copy:
      src: /etc/minikube_configs/client-deployment-4replicas.yml
      dest: /home/{{ansible_user}}/new_minikube_configs
      owner: "{{ansible_user}}"
      group: sudo

  - name: copy minikube deployment config to web
    ansible.builtin.copy:
      src: /etc/minikube_configs/client-deployment-service.yml
      dest: /home/{{ansible_user}}/new_minikube_configs
      owner: "{{ansible_user}}"
      group: sudo
      
  - name: apply the cluster with kubectl -restart minikube in case of error
    block:
      - name: apply the 4 replicas deployment
        ansible.builtin.shell: kubectl apply -f /home/{{ansible_user}}/new_minikube_configs/client-deployment-4replicas.yml
    
      - name: apply the 4 replicas service
        ansible.builtin.shell: kubectl apply -f /home/{{ansible_user}}/new_minikube_configs/client-deployment-service.yml

    rescue:
      - name: restart minikube
        ansible.builtin.shell: minikube start
        
      - name: apply the 4 replicas deployment
        ansible.builtin.shell: kubectl apply -f /home/{{ansible_user}}/new_minikube_configs/client-deployment-4replicas.yml
    
      - name: apply the 4 replicas service
        ansible.builtin.shell: kubectl apply -f /home/{{ansible_user}}/new_minikube_configs/client-deployment-service.yml
        
  - name: Pause for 25 sec to build app 
    ansible.builtin.pause:
      seconds: 25
      
  - name: ip check
    ansible.builtin.shell: hostname -I | awk '{print $1}'
    register: ip

  - name: Register dummy host with variable so we will be able to use on other hosts tasks
    add_host:
      name: "DUMMY_HOST"
      CLUSTER_HOST__IP: " {{ ip.stdout }}"
      
- name: run check for the output if not rollback
  hosts: localhost
  tasks:
  
  - name: run check for the output if not rollback
    ansible.builtin.shell: sudo python3 /etc/minikube_configs/test.py {{ hostvars['DUMMY_HOST']['CLUSTER_HOST__IP'] }}
    register: answer

  - debug:
      msg: "ip answer= {{ answer.stdout }}"

- name: run check for the output if not rollback
  hosts: web
  ansible.builtin.shell: sudo cp /home/{{ansible_user}}/new_minikube_configs/client-deployment-4replicas.yml /home/{{ansible_user}}/current_minikube_configs/client-deployment-4replicas.yml 
  when: '"pong" == "pong"'

   
    
   
   

    
        
