- name: copy and deploy cluster
  become: true
  gather_facts: false
  hosts: web
  vars:
    asnible_python_interpreter: /usr/bin/python3
  
  tasks:
  - name: ensures minikube conf dir exists
    file: 
      path: "/etc/minikube_configs"
      state: directory
      mode: '0755'

  - name: copy minikube deployment config to web1
    ansible.builtin.copy:
      src: /etc/minikube_configs/client-deployment-4replicas.yml
      dest: /etc/minikube_configs
      owner: root
      group: sudo

  - name: copy minikube deployment config to web1
    ansible.builtin.copy:
      src: /etc/minikube_configs/client-deployment-service.yml
      dest: /etc/minikube_configs
      owner: root
      group: sudo

  - name: apply the cluster with kubectl -restart minikube in case of error
    block:
      - name: apply the 4 replicas deployment
        ansible.builtin.shell: kubectl apply -f /etc/minikube_configs/client-deployment-4replicas.yml
    
      - name: apply the 4 replicas service
        ansible.builtin.shell: kubectl apply -f /etc/minikube_configs/client-deployment-service.yml
    rescue:
      - name: restart minikube
        ansible.builtin.shell: minikube start
        
      - name: apply the 4 replicas deployment
        ansible.builtin.shell: kubectl apply -f /etc/minikube_configs/client-deployment-4replicas.yml
    
      - name: apply the 4 replicas service
        ansible.builtin.shell: kubectl apply -f /etc/minikube_configs/client-deployment-service.yml
