- name: copy and deploy cluster
  hosts: web
  vars:
    asnible_python_interpreter: /usr/bin/python3
  become: true
  become_user: "{{ansible_user}}"
  
  tasks:
  - name: ensures minikube conf dir exists
    file: 
      path: "/home/{{ansible_user}}/minikube_configs"
      state: directory

  - name: copy minikube deployment config to web
    ansible.builtin.copy:
      src: /etc/minikube_configs/client-deployment-4replicas.yml
      dest: /home/{{ansible_user}}/minikube_configs
      owner: "{{ansible_user}}"
      group: sudo

  - name: copy minikube deployment config to web
    ansible.builtin.copy:
      src: /etc/minikube_configs/client-deployment-service.yml
      dest: /home/{{ansible_user}}/minikube_configs
      owner: "{{ansible_user}}"
      group: sudo
      
  - name: apply the cluster with kubectl -restart minikube in case of error
    block:
      - name: apply the 4 replicas deployment
        ansible.builtin.shell: kubectl apply -f /home/{{ansible_user}}/minikube_configs/client-deployment-4replicas.yml
    
      - name: apply the 4 replicas service
        ansible.builtin.shell: kubectl apply -f /home/{{ansible_user}}/minikube_configs/client-deployment-service.yml
    rescue:
      - name: restart minikube
        ansible.builtin.shell: minikube start
        
      - name: apply the 4 replicas deployment
        ansible.builtin.shell: kubectl apply -f /home/{{ansible_user}}/minikube_configs/client-deployment-4replicas.yml
    
      - name: apply the 4 replicas service
        ansible.builtin.shell: kubectl apply -f /home/{{ansible_user}}/minikube_configs/client-deployment-service.yml


  - name: ip check
    ansible.builtin.shell: hostname -I | awk '{print $1}'
    register: ip

  - name: Register dummy host with variable so we will be able to use on other hosts tasks
    add_host:
      name: "DUMMY_HOST"
      CLUSTER_HOST__IP: " {{ ip.stdout }}"
      
- name: run check for the output if not rollback
  hosts: localhost
  tasks:
  
  - name: Echo the output - PLAY1 variable vaule
    ansible.builtin.shell: cat {{ hostvars['DUMMY_HOST']['CLUSTER_HOST__IP'] }} |tail -1
    register: host__ip
  - debug: msg: "{{ host__ip }}"
  
  - name: run check for the output if not rollback
    ansible.builtin.shell: sudo python3 /etc/minikube_configs/test.py "{{ host__ip }}"
    register: answer

  - debug:
      msg: "{{ host__ip }} ip answer= {{ answer.stdout }}"
   
    
   
   

    
        
