- name: Run the test playbook
  gather_facts: false
  hosts: web

  tasks:
    - name: Create Folder
      file:
        path: /home/ansible/minkube_files
        owner: ansible
        group: sudo
        mode: 0755
        state: directory

    - name: copy minikube deployment config to web1
      ansible.builtin.copy:
        src: client-deployment-4replicas.yml
        dest: /home/ansible/minikube_files
        owner: ansible
        group: sudo

    - name: copy minikube deployment config to web1
      ansible.builtin.copy:
        src: client-deployment-service.yml
        dest: /home/ansible/minikube_files
        owner: ansible
        group: sudo
