- name: copy and deploy cluster
  hosts: web
  vars:
    asnible_python_interpreter: /usr/bin/python3
  become: true
  become_user: "{{ansible_user}}"
  
  tasks:
  - name: ensures minikube conf dir exists
    file: 
      path: "/home/{{ansible_user}}/minikube_configs"
      state: directory

  - name: copy minikube deployment config to web
    ansible.builtin.copy:
      src: /etc/minikube_configs/client-deployment-4replicas.yml
      dest: /home/{{ansible_user}}/minikube_configs
      owner: "{{ansible_user}}"
      group: sudo

  - name: copy minikube deployment config to web
    ansible.builtin.copy:
      src: /etc/minikube_configs/client-deployment-service.yml
      dest: /home/{{ansible_user}}/minikube_configs
      owner: "{{ansible_user}}"
      group: sudo
      
  - name: copy test.py
    ansible.builtin.copy:
      src: /etc/minikube_configs/test.py
      dest: /home/{{ansible_user}}/minikube_configs/test.py
      owner: "{{ansible_user}}"
      group: sudo
      
  - name: apply the cluster with kubectl -restart minikube in case of error
    block:
      - name: apply the 4 replicas deployment
        ansible.builtin.shell: kubectl apply -f /home/{{ansible_user}}/minikube_configs/client-deployment-4replicas.yml
    
      - name: apply the 4 replicas service
        ansible.builtin.shell: kubectl apply -f /home/{{ansible_user}}/minikube_configs/client-deployment-service.yml
    rescue:
      - name: restart minikube
        ansible.builtin.shell: minikube start
        
      - name: apply the 4 replicas deployment
        ansible.builtin.shell: kubectl apply -f /home/{{ansible_user}}/minikube_configs/client-deployment-4replicas.yml
    
      - name: apply the 4 replicas service
        ansible.builtin.shell: kubectl apply -f /home/{{ansible_user}}/minikube_configs/client-deployment-service.yml

  - name: run test.py
    ansible.builtin.shell: sudo python3 /home/{{ansible_user}}/minikube_configs/test.py

